/**
 * Created by Ronan Williams on 18/06/2018.
 */
@IsTest
public class QuickbooksBudgetCalloutTest {

    @IsTest
    public static void testBudgets() {

//        Test.startTest();
//        // Set mock callout class
//        Test.setMock(HttpCalloutMock.class, new QBOBudgetMock());
//
//        // Call method to test
//        QuickbooksBudgetCallout.getBudget();
//        Test.stopTest();
    }

}